"""add_recording_table

Revision ID: b2dd5d703b09
Revises: c9d494ac6699
Create Date: 2026-03-17 18:32:40.164143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dd5d703b09'
down_revision: Union[str, Sequence[str], None] = 'c9d494ac6699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('visit_id', sa.String(length=12), nullable=True),
    sa.Column('staff_id', sa.String(length=12), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('transcript_segments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_recordings_staff_id_staff'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_recordings_visit_id_visits'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordings')
    # ### end Alembic commands ###
