"""add_customer_and_visit_tables

Revision ID: c9d494ac6699
Revises: c3c6f6f0e2ab
Create Date: 2026-03-17 18:18:47.270292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d494ac6699'
down_revision: Union[str, Sequence[str], None] = 'c3c6f6f0e2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('wechat_external_uid', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('phone', name=op.f('uq_customers_phone')),
    sa.UniqueConstraint('wechat_external_uid', name=op.f('uq_customers_wechat_external_uid'))
    )
    op.create_table('visits',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('customer_id', sa.String(length=12), nullable=False),
    sa.Column('consultant_id', sa.String(length=12), nullable=True),
    sa.Column('doctor_id', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('deposit_principal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_bonus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['staff.id'], name=op.f('fk_visits_consultant_id_staff'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_visits_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.id'], name=op.f('fk_visits_doctor_id_staff'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('customers')
    # ### end Alembic commands ###
