"""add_transcript_and_segment_tables

Revision ID: cab9cc12ed8d
Revises: b2dd5d703b09
Create Date: 2026-03-17 18:53:09.675129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab9cc12ed8d'
down_revision: Union[str, Sequence[str], None] = 'b2dd5d703b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('recording_id', sa.String(length=12), nullable=False),
    sa.Column('visit_id', sa.String(length=12), nullable=True),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('begin_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('utterances', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_segments_recording_id_recordings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('fk_segments_visit_id_visits'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments'))
    )
    op.create_table('transcripts',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('recording_id', sa.String(length=12), nullable=False),
    sa.Column('asr_provider', sa.String(length=50), nullable=False),
    sa.Column('asr_task_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('utterances', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_transcripts_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('recording_id', name=op.f('uq_transcripts_recording_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('segments')
    # ### end Alembic commands ###
