#!/usr/bin/env bash
set -euo pipefail

cd /opt/badge/apps/api

unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY all_proxy ALL_PROXY

export DINGTALK_AUDIO_SYNC_ENABLED=true
export DINGTALK_AUDIO_ARCHIVE_SYNC_ENABLED=true
export DINGTALK_AUDIO_BACKLOG_SYNC_ENABLED=true
export DINGTALK_AUDIO_PIPELINE_WORKERS="${DINGTALK_AUDIO_PIPELINE_WORKERS:-2}"
export DINGTALK_AUDIO_ARCHIVE_SYNC_WORKERS="${DINGTALK_AUDIO_ARCHIVE_SYNC_WORKERS:-1}"
export DINGTALK_AUDIO_BACKLOG_SYNC_WORKERS="${DINGTALK_AUDIO_BACKLOG_SYNC_WORKERS:-1}"
export TENCENT_ASR_MAX_CONCURRENCY="${TENCENT_ASR_MAX_CONCURRENCY:-3}"
export ASR_AUDIO_QUALITY_DIAGNOSTICS_ENABLED="${ASR_AUDIO_QUALITY_DIAGNOSTICS_ENABLED:-false}"

exec /home/ymailancy/.local/bin/uv run python -m smart_badge_api.audio_worker
